- hosts: batch
  become: yes
  remote_user: batch
  gather_facts: no
  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Tokyo
    - name: Install apt packages
      apt:
        name:
          - dotnet-sdk-8.0
          - openjdk-8-jdk
        state: present
        update_cache: yes
  handlers:
