- hosts: batch
  become: yes
  remote_user: batch
  gather_facts: no

  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Tokyo

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present