- hosts: database
  become: yes
  remote_user: database
  gather_facts: no
  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Tokyo
    - name: apt update
      apt:
        update_cache: yes
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: no
      with_items:
        - mariadb-server
        - python3-pymysql
    - name: create mariadb databases
      mysql_db:
        login_user: database
        login_password: "{{ mysql.database.password }}"
        name: "{{ item.name }}"
        state: present
        encoding: utf8mb4
      with_items:
        - "{{ mysql.databases }}"
    - name: create mariadb users
      mysql_user:
        login_user: database
        login_password: "{{ mysql.database.password }}"
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        priv: "{{ item.priv }}"
        host: "%"
        state: present
      with_items:
        - "{{ mysql.users }}"
    - name: Add cron jobs
      cron:
        name: "{{ item.name }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
        job: "{{ item.job }}"
        state: present
      with_items:
        - {
            name: データベースバックアップ,
            minute: "34",
            hour: "*",
            job: "mysqldump -uroot -p{{ mysql.root.password }} -A --ignore-table=mysql.* --ignore-table=information_schema.* --ignore-table=performance_schema.* --extended-insert --single-transaction > database.dump",
          }
