- hosts: home
  become: yes
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Tokyo
    - name: Download MS product repository
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: Install MS product repository
      apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: Make sure HTTPS is supported by apt
      apt:
        name: apt-transport-https
        state: present
        update_cache: no
    - name: Install .NET Core SDK
      apt:
        name: dotnet-sdk-3.1
        state: present
        update_cache: yes
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present
        update_cache: yes
    - name: Install Java11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
    - name: Import the GPG keys of the Jenkins repository
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
    - name: Add the Jenkins repository to the system
      lineinfile:
        path: /etc/apt/sources.list.d/jenkins.list
        state: present
        owner: root
        group: root
        mode: "0644"
        create: yes
        line: "deb http://pkg.jenkins.io/debian-stable binary/"
    - name: Install jenkins
      apt:
        force_apt_get: yes
        name: jenkins
        state: present
        update_cache: yes
    - name: Install pymysql
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes
    - name: create mariadb databases
      mysql_db:
        login_user: ubuntu
        login_password: "{{ mysql.ubuntu.password }}"
        name: "{{ item.name }}"
        state: present
        encoding: utf8mb4
      with_items:
        - "{{ mysql.databases }}"
    - name: create mariadb users
      mysql_user:
        login_user: ubuntu
        login_password: "{{ mysql.ubuntu.password }}"
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        priv: "{{ item.priv }}"
        host: "%"
        state: present
      with_items:
        - "{{ mysql.users }}"
    - name: Install the package "nginx"
      apt:
        name: nginx
        state: present
    - name: Copy nginx.conf
      copy:
        src: ./home_server/nginx/default.conf
        dest: /etc/nginx/sites-available/default
      notify:
        - restart nginx
    - name: Add cron config financial information update request
      cron:
        name: 財務情報定期更新
        minute: "*/10"
        hour: "*"
        job: 'curl --location --request POST ''http://home-server.localnet/api/financial-api/post-update-by-span-request'' --header ''Content-Type: application/json'' --data-raw ''{"Days": 60}'''
        state: present
    - name: Add back end api service
      copy:
        src: ./home_server/services/servicefiles/back_end_api.service
        dest: /etc/systemd/system/back_end_api.service
      notify:
        - restart back end api service
    - name: Enable back end api service
      service:
        name: back_end_api
        enabled: yes
      notify:
        - restart back end api service
    - name: Install the package "wakeonlan"
      apt:
        name: wakeonlan
        state: present
    - name:
      cron:
        name: oui更新
        minute: "44"
        hour: "4"
        job: "curl --location --request POST 'http://home-server.localnet/api/network-api/post-update-vendor-list-request' --header 'Content-Type: application/json'"
        state: present
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart back end api service
      service: name=back_end_api state=restarted
