- hosts: home
  become: yes
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Tokyo
    - name: Download MS product repository
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: Install MS product repository
      apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: Make sure HTTPS is supported by apt
      apt:
        name: apt-transport-https
        state: present
        update_cache: no
    - name: Install .NET Core SDK
      apt:
        name: dotnet-sdk-3.1
        state: present
        update_cache: yes
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present
        update_cache: yes
    - name: Install pymysql
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes
    - name: create mariadb databases
      mysql_db:
        login_user: ubuntu
        login_password: "{{ mysql.ubuntu.password }}"
        name: "{{ item.name }}"
        state: present
        encoding: utf8mb4
      with_items:
        - "{{ mysql.databases }}"
    - name: create mariadb users
      mysql_user:
        login_user: ubuntu
        login_password: "{{ mysql.ubuntu.password }}"
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        priv: "{{ item.priv }}"
        host: "%"
        state: present
      with_items:
        - "{{ mysql.users }}"
    - name: Install the package "nginx"
      apt:
        name: nginx
        state: present
    - name: Copy nginx.conf
      copy:
        src: ./home_server/nginx/default.conf
        dest: /etc/nginx/sites-available/default
      notify:
        - restart nginx
    - name: Add cron config financial information update request
      cron:
        name: 財務情報定期更新
        minute: "*/10"
        hour: "*"
        job: 'curl --location --request POST ''http://home-server.localnet/api/financial-api/post-update-by-span-request'' --header ''Content-Type: application/json'' --data-raw ''{"Days": 60}'''
        state: present
    - name: Add back end api service
      copy:
        src: ./home_server/services/servicefiles/back_end_api.service
        dest: /etc/systemd/system/back_end_api.service
      notify:
        - restart back end api service
    - name: Enable back end api service
      service:
        name: back_end_api
        enabled: yes
      notify:
        - restart back end api service
    - name: Install the package "wakeonlan"
      apt:
        name: wakeonlan
        state: present
    - name:
      cron:
        name: oui更新
        minute: "44"
        hour: "4"
        job: "curl --location --request POST 'http://home-server.localnet/api/network-api/post-update-vendor-list-request' --header 'Content-Type: application/json'"
        state: present
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart back end api service
      service: name=back_end_api state=restarted
- hosts: dhcp
  become: yes
  remote_user: pi
  gather_facts: no
  tasks:
    - name: Set timezone
      timezone:
        name: Asia/Tokyo
    - name: Install the package "dnsmasq"
      apt:
        name: dnsmasq
        update_cache: yes
        state: present
    - name: Copy dnsmasq.conf
      copy:
        src: ./raspi_dhcp/dnsmasq/dnsmasq.conf
        dest: /etc/dnsmasq.conf
      notify:
        - restart dnsmasq
    - name: Copy dnsmasq-hosts
      copy:
        src: ./raspi_dhcp/dnsmasq/dnsmasq-hosts
        dest: /etc/dnsmasq-hosts
      notify:
        - restart dnsmasq

    - name: Install the package "nginx"
      apt:
        name: nginx
        state: present
    - name: Synchronize html files
      synchronize:
        src: ./raspi_dhcp/nginx/html/
        dest: /var/www/html/
        recursive: yes
        delete: yes
    - name: Copy nginx.conf
      copy:
        src: ./raspi_dhcp/nginx/default.conf
        dest: /etc/nginx/sites-available/default
      notify:
        - restart nginx

    - name: Install the package "php7.3"
      apt:
        name: php7.3
        state: present
    - name: Install the package "php7.3-fpm"
      apt:
        name: php7.3-fpm
        state: present
    - name: Copy php-fpm.conf
      copy:
        src: ./raspi_dhcp/php/php-fpm.conf
        dest: /etc/php/7.3/fpm/php-fpm.conf
      notify:
        - restart php7.3-fpm
    - name: Copy php.ini
      copy:
        src: ./raspi_dhcp/php/php.ini
        dest: /etc/php/7.3/fpm/php.ini
      notify:
        - restart php7.3-fpm
    - name: Copy www.conf
      copy:
        src: ./raspi_dhcp/php/www.conf
        dest: /etc/php/7.3/fpm/pool.d/www.conf
      notify:
        - restart php7.3-fpm
    - name: Install the package "python3.7.3-1"
      apt:
        name:
          - python3-dev=3.7.3-1
    - name: mkdir /services/dhcp_assign_notifier
      file:
        path: /home/pi/services/dhcp_assign_notifier
        state: directory
        owner: pi
        group: pi
        mode: 0755
    - name: Publish dhcp_assign_notifier
      synchronize:
        src: ./raspi_dhcp/services/dhcp_assign_notifier/
        dest: /home/pi/services/dhcp_assign_notifier/
        recursive: yes
        delete: yes
      notify:
        - restart dhcp_assign_notifier
    - name: Add services
      synchronize:
        src: ./raspi_dhcp/services/servicefiles/
        dest: /etc/systemd/system/
        recursive: yes
        delete: no
    - name: Enable dhcp_assign_notifier
      service:
        name: dhcp_assign_notifier
        enabled: yes
      notify:
        - restart dhcp_assign_notifier
    - name: mkdir /var/lib/myscripts/
      file:
        path: /var/lib/myscripts/
        state: directory
        owner: root
        group: root
        mode: 0755
    - name:
      cron:
        name: oui更新
        minute: "44"
        hour: "4"
        job: "wget https://standards.ieee.org/develop/regauth/oui/oui.csv -O /var/lib/myscripts/oui.csv"
        state: present
      notify:
        - download oui.csv
  handlers:
    - name: restart dnsmasq
      service: name=dnsmasq state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php7.3-fpm
      service: name=php7.3-fpm state=restarted
    - name: restart dhcp_assign_notifier
      service: name=dhcp_assign_notifier state=restarted
    - name: download oui.csv
      get_url:
        url: https://standards.ieee.org/develop/regauth/oui/oui.csv
        dest: /var/lib/myscripts/oui.csv
