- name: home_server
  import_playbook: ./home_server.yaml
- name: raspi_dhcp
  import_playbook: ./raspi_dhcp.yaml
- name: aquarium
  import_playbook: ./aquarium.yaml
- name: db_server
  import_playbook: ./db_server.yaml
- name: watch_server
  import_playbook: ./watch_server.yaml
